export const PROJECT_SHARE_LINK_EXPIRY_DAYS = 7;
export const PROJECT_SHARE_PASSWORD_MAX_ATTEMPTS = 5;
export const PROJECT_SHARE_PASSWORD_LOCKOUT_MINUTES = 15;
export const PROJECT_SHARE_PASSWORD_LENGTH = 12;
export const PROJECT_FILE_DELETION_LOCK_HOURS = 24;
